"""Extended CLI tests: fingerprint, dangerous dir, adapt operations, zh-TW."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from vibe_state.cli import app

runner = CliRunner()


class TestFingerprint:
    def test_start_warns_on_foreign_vibe(self, tmp_path: Path) -> None:
        """vibe start warns when .vibe/ was not generated locally."""
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)

        (tmp_path / ".git").mkdir()
        # Create .vibe/ manually (simulating a cloned repo)
        vibe = tmp_path / ".vibe"
        (vibe / "state").mkdir(parents=True)
        (vibe / "VIBE.md").write_text("# VIBE\n")
        (vibe / "config.toml").write_text('[vibe]\nversion = 1\n')
        (vibe / "state" / ".lifecycle").write_text("READY\n")

        result = runner.invoke(app, ["start"])
        assert "not generated on this machine" in result.output
        monkeypatch.undo()

    def test_start_no_warning_after_init(self, tmp_path: Path) -> None:
        """vibe start does NOT warn when .vibe/ was generated by init."""
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)

        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])
        result = runner.invoke(app, ["start"])
        assert "not generated on this machine" not in result.output
        monkeypatch.undo()


class TestDangerousDirectory:
    def test_init_blocked_in_home(self, tmp_path: Path) -> None:
        """init refuses to run in HOME directory."""
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(Path.home())
        result = runner.invoke(app, ["init"])
        assert result.exit_code == 1
        assert "HOME or root" in result.output
        monkeypatch.undo()


class TestAdaptOperations:
    def test_adapt_remove_dry_run(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])
        runner.invoke(app, ["adapt", "--add", "claude"])
        runner.invoke(app, ["adapt", "--sync", "--confirm"])

        result = runner.invoke(app, ["adapt", "--remove", "claude", "--dry-run"])
        assert "dry-run" in result.output
        # Files should still exist
        assert (tmp_path / "CLAUDE.md").exists()
        monkeypatch.undo()

    def test_adapt_remove_confirm(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])
        runner.invoke(app, ["adapt", "--add", "claude"])
        runner.invoke(app, ["adapt", "--sync", "--confirm"])

        result = runner.invoke(app, ["adapt", "--remove", "claude", "--confirm"])
        assert result.exit_code == 0
        # Backup should exist
        backup_dir = tmp_path / ".vibe" / "backups" / "claude"
        assert backup_dir.exists()
        monkeypatch.undo()

    def test_adapt_sync_regenerates(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])
        runner.invoke(app, ["adapt", "--add", "cursor"])

        result = runner.invoke(app, ["adapt", "--sync", "--confirm"])
        assert "synced" in result.output
        assert (tmp_path / ".cursor" / "rules" / "vibe-standards.mdc").exists()
        monkeypatch.undo()

    def test_adapt_add_invalid(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])
        result = runner.invoke(app, ["adapt", "--add", "nonexistent"])
        assert result.exit_code == 1
        assert "Unknown adapter" in result.output
        monkeypatch.undo()


class TestInitForce:
    def test_force_creates_backup(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])

        # Customize VIBE.md
        vibe_md = tmp_path / ".vibe" / "VIBE.md"
        vibe_md.write_text("# Custom VIBE\n")

        result = runner.invoke(app, ["init", "--force"])
        assert result.exit_code == 0
        assert "Backed up" in result.output
        monkeypatch.undo()


class TestZhTW:
    def test_init_zh_tw(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()

        result = runner.invoke(app, ["init", "--lang", "zh-TW"])
        assert result.exit_code == 0

        vibe_md = (tmp_path / ".vibe" / "VIBE.md").read_text(encoding="utf-8")
        assert "專案憲法" in vibe_md
        monkeypatch.undo()

    def test_init_invalid_lang_fallback(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()

        result = runner.invoke(app, ["init", "--lang", "xx"])
        assert "not a supported language" in result.output
        assert result.exit_code == 0  # Falls back to en
        monkeypatch.undo()


class TestIntegrityHash:
    def test_adapter_files_have_integrity_marker(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])

        agents_md = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
        assert "<!-- vibe-state-cli:integrity:" in agents_md
        monkeypatch.undo()

    def test_json_files_no_integrity_marker(self, tmp_path: Path) -> None:
        """JSON files should NOT have HTML integrity marker."""
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        (tmp_path / ".claude").mkdir()
        runner.invoke(app, ["init"])

        settings = tmp_path / ".claude" / "settings.json"
        if settings.exists():
            content = settings.read_text(encoding="utf-8")
            assert "<!-- vibe-state-cli" not in content
            # Verify it's valid JSON
            import json
            json.loads(content)  # Should not raise
        monkeypatch.undo()


class TestVibeGitignore:
    def test_init_creates_internal_gitignore(self, tmp_path: Path) -> None:
        monkeypatch = pytest.MonkeyPatch()
        monkeypatch.chdir(tmp_path)
        (tmp_path / ".git").mkdir()
        runner.invoke(app, ["init"])

        gi = tmp_path / ".vibe" / ".gitignore"
        assert gi.exists()
        content = gi.read_text(encoding="utf-8")
        assert "snapshots/" in content
        assert "backups/" in content
        assert ".fingerprint" in content
        monkeypatch.undo()
