"""CLI entry point for vibe-state-cli.

5 commands: init, start, sync, status, adapt
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from vibe_state.adapters.base import build_adapter_context
from vibe_state.adapters.registry import get_adapter
from vibe_state.config import VibeConfig, load_config, save_config
from vibe_state.core.compactor import compact_tasks
from vibe_state.core.git_ops import (
    detect_experiment_commits,
    get_diff_stat,
    get_head_hash,
    get_log_since,
    get_status,
    git_available,
    read_sync_cursor,
    write_sync_cursor,
)
from vibe_state.core.lifecycle import (
    LifecycleError,
    LifecycleState,
    check_transition,
    read_state,
    write_state,
)
from vibe_state.core.scanner import scan_project
from vibe_state.core.state import (
    append_to_state_file,
    get_file_line_count,
    read_state_file,
    validate_state_dir,
    write_state_file,
)
from vibe_state.core.templates import render_all_state_files

app = typer.Typer(
    name="vibe",
    help="Model-agnostic AI-human collaboration state management CLI.",
    no_args_is_help=True,
)
console = Console()


def _vibe_dir() -> Path:
    return Path.cwd() / ".vibe"


def _require_lifecycle(command: str) -> LifecycleState:
    """Check lifecycle transition and return next state. Exit on error."""
    try:
        return check_transition(_vibe_dir(), command)
    except LifecycleError as e:
        console.print(f"[bold red]Error:[/] {e}")
        raise typer.Exit(1) from None


def _extract_latest_progress(content: str) -> str:
    """Extract the most recent Sync block or progress summary from current.md."""
    lines = content.splitlines()
    # Walk backwards to find the last "## Sync" or "## Final Sync" block
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].startswith("## Sync") or lines[i].startswith("## Final Sync"):
            # Return the header + next non-empty content line
            header = lines[i].strip()
            for j in range(i + 1, min(i + 5, len(lines))):
                if lines[j].strip() and not lines[j].startswith("```"):
                    return f"{header} — {lines[j].strip()}"
            return header
    # Fallback: first non-header, non-blockquote line under "## Progress"
    in_progress = False
    for line in lines:
        if "Progress" in line and line.startswith("#"):
            in_progress = True
            continue
        if in_progress and line.strip() and not line.startswith("#"):
            return line.strip()
    return "(no progress recorded yet)"


def _extract_section_items(content: str, section_name: str) -> list[str]:
    """Extract bullet items under a specific ## section."""
    lines = content.splitlines()
    in_section = False
    items: list[str] = []
    for line in lines:
        if line.startswith("## ") and section_name in line:
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section and line.strip().startswith("- "):
            item = line.strip()
            if item != "- (none)":
                items.append(item)
    return items


def _sanitize_name(name: str) -> str:
    """Sanitize a project/adapter name: strip newlines, #, and control chars."""
    return "".join(c for c in name if c.isprintable() and c not in "\n\r#")


def _write_fingerprint(vibe_dir: Path) -> None:
    """Write a random UUID fingerprint to mark .vibe/ as locally generated.

    Uses UUID (not hostname) to avoid GDPR concerns with PII.
    """
    import uuid

    fp_path = vibe_dir / ".fingerprint"
    token = str(uuid.uuid4())
    fp_path.write_text(f"vibe-state-cli:{token}\n", encoding="utf-8", newline="\n")

    # Also store the token in a user-local file for verification
    local_marker = Path.home() / ".vibe-fingerprints"
    local_marker.mkdir(parents=True, exist_ok=True)
    project_id = vibe_dir.resolve().as_posix()
    (local_marker / "known").write_text(
        _read_known_fingerprints(local_marker) + f"{project_id}={token}\n",
        encoding="utf-8",
        newline="\n",
    )


def _read_known_fingerprints(local_marker: Path) -> str:
    known_file = local_marker / "known"
    if known_file.exists():
        return known_file.read_text(encoding="utf-8")
    return ""


def _check_fingerprint(vibe_dir: Path) -> bool:
    """Check if .vibe/ was generated by this user. Returns True if safe."""
    fp_path = vibe_dir / ".fingerprint"
    if not fp_path.exists():
        return False

    token = fp_path.read_text(encoding="utf-8").strip().removeprefix("vibe-state-cli:")
    if not token:
        return False

    # Check against user-local known fingerprints
    local_marker = Path.home() / ".vibe-fingerprints"
    known = _read_known_fingerprints(local_marker)
    project_id = vibe_dir.resolve().as_posix()
    return f"{project_id}={token}" in known


def _check_dangerous_directory() -> None:
    """Warn if running in HOME or root directory."""
    cwd = Path.cwd().resolve()
    dangerous = [Path.home().resolve(), Path("/").resolve()]
    if cwd in dangerous:
        console.print(
            "[bold red]Warning:[/] You are in your HOME or root directory.\n"
            "Running vibe init here will pollute this directory with .vibe/ files.\n"
            "Please cd into a project directory first."
        )
        raise typer.Exit(1)


# ─── vibe init ───────────────────────────────────────────────────────────────


@app.command()
def init(
    lang: str = typer.Option("en", help="Template language: en, zh-TW"),
    force: bool = typer.Option(False, help="Force reinitialize (also reopens closed projects)"),
) -> None:
    """Initialize .vibe/ directory in the current project."""
    _check_dangerous_directory()
    vibe_dir = _vibe_dir()

    if (vibe_dir / "VIBE.md").exists() and not force:
        console.print("[yellow]Warning:[/] .vibe/ already exists. Use --force to reinitialize.")
        raise typer.Exit(1)

    # H1: Backup existing .vibe/ before --force overwrite
    if force and vibe_dir.exists():
        from vibe_state.safety import create_backup

        existing_files = list(vibe_dir.glob("*.md")) + list(vibe_dir.glob("state/*.md"))
        if existing_files:
            backup_dir = create_backup(vibe_dir, "_reinit", existing_files)
            console.print(f"[dim]Backed up existing .vibe/ to {backup_dir.name}[/]")

    if not force:
        _require_lifecycle("init")

    # Validate language
    from vibe_state.core.templates import SUPPORTED_LANGS

    if lang not in SUPPORTED_LANGS:
        console.print(
            f"[yellow]Warning:[/] '{lang}' is not a supported language. "
            f"Supported: {', '.join(sorted(SUPPORTED_LANGS))}. Falling back to 'en'."
        )
        lang = "en"

    # Phase 1: Scan project
    console.print("[bold]Scanning project...[/]")
    scan = scan_project(Path.cwd())

    # Phase 2: Detect adapters or default
    selected_adapters = scan.detected_tools.copy()
    if not selected_adapters:
        selected_adapters = ["agents_md"]
        console.print(
            "[dim]No AI tools detected. Defaulting to AGENTS.md (universal standard).[/]"
        )

    if "agents_md" not in selected_adapters:
        selected_adapters.append("agents_md")

    # Phase 3: Render templates
    config = VibeConfig()
    config.vibe.lang = lang
    config.adapters.enabled = selected_adapters
    config.git.enabled = scan.has_git

    files = render_all_state_files(
        languages=scan.languages,
        frameworks=scan.frameworks,
        project_name=_sanitize_name(Path.cwd().name),
        compact_threshold=config.state.compact_threshold,
        stale_task_days=config.state.stale_task_days,
        lang=lang,
    )

    # Phase 4: Write files
    for rel_path, content in files.items():
        full_path = vibe_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8", newline="\n")

    save_config(vibe_dir, config)
    write_state(vibe_dir, LifecycleState.READY)

    # Write fingerprint (supply chain protection)
    _write_fingerprint(vibe_dir)

    # Write internal .gitignore for snapshots/backups
    internal_gitignore = vibe_dir / ".gitignore"
    if not internal_gitignore.exists():
        internal_gitignore.write_text(
            "# vibe-state-cli internals (do not commit)\nsnapshots/\nbackups/\n.fingerprint\n",
            encoding="utf-8",
            newline="\n",
        )

    # Phase 5: Emit adapter files
    from vibe_state.safety import save_snapshot

    ctx = build_adapter_context(Path.cwd())
    adapter_files: list[str] = []
    for adapter_name in selected_adapters:
        adapter = get_adapter(adapter_name)
        if adapter:
            emitted = adapter.emit(ctx)
            save_snapshot(vibe_dir, adapter_name, emitted)
            adapter_files.extend(str(f.relative_to(Path.cwd())) for f in emitted)

    # Summary
    console.print()
    adapter_summary = (
        "\n".join(f"  - {f}" for f in adapter_files) if adapter_files else "  (none)"
    )
    console.print(Panel.fit(
        f"[bold green].vibe/ initialized successfully![/]\n\n"
        f"Languages: {', '.join(scan.languages) or 'none detected'}\n"
        f"Frameworks: {', '.join(scan.frameworks) or 'none detected'}\n"
        f"Git: {'yes' if scan.has_git else 'no'}\n"
        f"Adapters: {', '.join(selected_adapters)}\n\n"
        f"Generated files:\n{adapter_summary}\n\n"
        f"[dim]Tip: commit .vibe/ to git so your team shares the same brain.[/dim]\n"
        f"[dim]Next: run [bold]vibe start[/bold] to begin your session.[/dim]",
        title="vibe init",
    ))


# ─── vibe start ──────────────────────────────────────────────────────────────


@app.command()
def start() -> None:
    """Load state, validate against git, auto-compact, output status summary."""
    vibe_dir = _vibe_dir()
    next_state = _require_lifecycle("start")

    # Supply chain protection: warn if .vibe/ was not generated on this machine
    if not _check_fingerprint(vibe_dir):
        console.print(
            "[bold yellow]Warning:[/] This .vibe/ was not generated on this machine.\n"
            "It may have come from a cloned repository. Review .vibe/VIBE.md\n"
            "for unexpected instructions before proceeding.\n"
            "[dim]Run [bold]vibe init --force[/bold] to regenerate and claim ownership.[/dim]\n"
        )

    config = load_config(vibe_dir)

    # Validate state files exist
    missing = validate_state_dir(vibe_dir)
    if missing:
        console.print(f"[yellow]Warning:[/] Missing state files: {', '.join(missing)}")

    # Auto-compact if any file exceeds threshold
    threshold = config.state.compact_threshold
    for fname in ["current.md", "tasks.md", "standards.md", "architecture.md"]:
        lines = get_file_line_count(vibe_dir, fname)
        if lines > threshold:
            console.print(
                f"[yellow]Auto-compacting:[/] {fname} has {lines} lines (>{threshold})"
            )
            compact_tasks(vibe_dir, stale_days=config.state.stale_task_days)
            break

    # Git validation
    git_info = ""
    if config.git.enabled and git_available():
        changed = get_status(Path.cwd())
        git_info = f"{len(changed)} uncommitted changes" if changed else "clean"
    elif not config.git.enabled:
        git_info = "disabled"
    else:
        git_info = "git not found"

    # Read current state for summary
    current = read_state_file(vibe_dir, "current.md")
    tasks = read_state_file(vibe_dir, "tasks.md")

    # Extract latest progress: find last "## Sync" or "## Progress" block
    progress = _extract_latest_progress(current)

    # Extract open issues (lines starting with "- " under "## Open Issues")
    open_issues = _extract_section_items(current, "Open Issues")

    # Extract top 3 pending tasks
    pending: list[str] = []
    for line in tasks.splitlines():
        if line.strip().startswith("- [ ]") and len(pending) < 3:
            pending.append(line.strip().removeprefix("- [ ]").strip())

    # Extract experiment summary
    experiments = read_state_file(vibe_dir, "experiments.md")
    exp_summary = ""
    if experiments:
        kept = experiments.count("[KEPT]")
        reverted = experiments.count("[REVERTED]")
        if kept or reverted:
            exp_summary = f"{kept} kept, {reverted} reverted"

    write_state(vibe_dir, next_state)

    # Output Rich summary
    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="bold cyan")
    table.add_column()
    table.add_row("Progress", progress)
    table.add_row("Git", git_info)
    table.add_row(
        "Open issues",
        "\n".join(open_issues) if open_issues else "(none)",
    )
    if pending:
        table.add_row("Top tasks", "")
        for i, task in enumerate(pending, 1):
            table.add_row("", f"  {i}. {task}")
    else:
        table.add_row("Top tasks", "(none)")
    if exp_summary:
        table.add_row("Experiments", exp_summary)

    console.print()
    console.print(Panel(table, title="[bold]vibe start[/]", subtitle="Session loaded"))


# ─── vibe sync ───────────────────────────────────────────────────────────────


@app.command()
def sync(
    compact: bool = typer.Option(False, help="Run memory compaction after sync"),
    close: bool = typer.Option(False, help="Close project: final sync + compact + retrospective"),
) -> None:
    """Sync state from git. Use --compact to archive tasks, --close to end project."""
    vibe_dir = _vibe_dir()

    if close:
        next_state = _require_lifecycle("close")
    else:
        _require_lifecycle("sync")

    config = load_config(vibe_dir)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")

    # ── Git sync ──
    has_changes = False
    if config.git.enabled and git_available():
        root = Path.cwd()
        last_sync = read_sync_cursor(vibe_dir)
        commits = get_log_since(root, last_sync)
        diff_stat = get_diff_stat(root, last_sync)
        head = get_head_hash(root)

        # Skip if nothing changed (avoid empty sync blocks)
        if not commits and not diff_stat and not close:
            console.print("[dim]No changes since last sync.[/]")
        else:
            has_changes = True
            label = "Final Sync" if close else "Sync"
            block_lines = [
                f"\n## {label} [{now}]",
                f"Commits: {len(commits)} since last sync",
            ]
            if commits:
                block_lines.append("```")
                for c in commits[:20]:
                    block_lines.append(c)
                if len(commits) > 20:
                    block_lines.append(f"... and {len(commits) - 20} more")
                block_lines.append("```")
            if diff_stat:
                block_lines.append(f"\nFiles changed:\n```\n{diff_stat}\n```")

            sync_block = "\n".join(block_lines) + "\n"
            append_to_state_file(vibe_dir, "current.md", sync_block)
            write_sync_cursor(vibe_dir, head)

            console.print(
                f"[green]Synced:[/] {len(commits)} commits appended to state/current.md"
            )

            # Detect autoresearch experiment commits
            experiments = detect_experiment_commits(root, last_sync)
            if experiments:
                kept = sum(1 for e in experiments if not e.is_revert)
                reverted = sum(1 for e in experiments if e.is_revert)
                summary = f"{len(experiments)} iterations ({kept} kept, {reverted} reverted)"
                exp_lines = [f"\n## Experiments [{now}]", f"Detected: {summary}", ""]
                for exp in experiments:
                    status = "REVERTED" if exp.is_revert else "KEPT"
                    exp_lines.append(f"- [{status}] `{exp.hash}` {exp.message}")
                exp_lines.append("")
                append_to_state_file(vibe_dir, "experiments.md", "\n".join(exp_lines) + "\n")
                console.print(f"[cyan]Experiments:[/] {kept} kept, {reverted} reverted")
    else:
        append_to_state_file(
            vibe_dir, "current.md",
            f"\n## Sync [{now}]\n(No git — please update manually)\n",
        )
        console.print("[yellow]No git available.[/] Manual sync block appended.")

    # ── Compact (if --compact or --close) ──
    if compact or close:
        result = compact_tasks(vibe_dir, stale_days=config.state.stale_task_days)
        console.print(
            f"[green]Compacted:[/] {result.archived_tasks} tasks archived, "
            f"current.md {result.current_before_lines} → {result.current_after_lines} lines"
        )

    # ── Close (if --close) ──
    if close:
        retro = (
            f"# Project Retrospective\n\n"
            f"Generated: {now}\n\n"
            f"## Deliverables\n\n- [Fill in major deliverables]\n\n"
            f"## Key Technical Decisions\n\n- [Fill in decisions and rationale]\n\n"
            f"## Remaining Items\n\n- [Unfinished features, known bugs, tech debt]\n\n"
            f"## Lessons Learned\n\n- [Best practices to carry forward]\n"
        )
        write_state_file(vibe_dir, "retrospective.md", retro)
        write_state(vibe_dir, next_state)
        console.print(Panel(
            "Final sync + compact completed.\n"
            "Retrospective template: state/retrospective.md\n"
            "Project is now [bold]CLOSED[/].\n\n"
            "[dim]Use [bold]vibe init --force[/bold] to reopen.[/dim]",
            title="[bold]vibe sync --close[/]",
        ))
        return

    # ── C.L.E.A.R. checklist (only when there were actual changes) ──
    if not has_changes:
        return
    console.print()
    console.print(Panel(
        "[C] Core Logic   — Is the core logic correct? Edge cases?\n"
        "[L] Layout       — Structure/naming follows standards.md?\n"
        "[E] Evidence     — Test output or API response as proof?\n"
        "[A] Access       — Any hardcoded secrets or permission holes?\n"
        "[R] Refactor     — Obvious tech debt or performance issues?",
        title="[bold]C.L.E.A.R. Review Checklist[/]",
    ))


# ─── vibe status ─────────────────────────────────────────────────────────────


@app.command()
def status() -> None:
    """Show current project state summary (available in any lifecycle state)."""
    vibe_dir = _vibe_dir()

    if not vibe_dir.exists():
        console.print("[yellow]No .vibe/ directory found.[/] Run [bold]vibe init[/] first.")
        raise typer.Exit(1)

    lifecycle = read_state(vibe_dir)
    config = load_config(vibe_dir)

    # Count tasks
    tasks_content = read_state_file(vibe_dir, "tasks.md")
    task_lines = tasks_content.splitlines()
    pending = sum(1 for ln in task_lines if ln.strip().startswith("- [ ]"))
    done = sum(1 for ln in task_lines if ln.strip().startswith("- [x]"))
    stale = sum(1 for ln in task_lines if ln.strip().startswith("- [~]"))

    # File sizes
    file_lines: dict[str, int] = {}
    for fname in ["current.md", "tasks.md", "standards.md", "architecture.md", "archive.md"]:
        file_lines[fname] = get_file_line_count(vibe_dir, fname)

    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="bold cyan")
    table.add_column()
    table.add_row("Lifecycle", lifecycle.value)
    table.add_row("Language", config.vibe.lang)
    table.add_row("Adapters", ", ".join(config.adapters.enabled))
    table.add_row("Git", "enabled" if config.git.enabled else "disabled")
    table.add_row("Tasks", f"{pending} pending, {done} done, {stale} stale")
    table.add_row("", "")
    table.add_row("File lines", "")
    for fname, lines in file_lines.items():
        marker = " [yellow](!)[/]" if lines > config.state.compact_threshold else ""
        table.add_row("", f"  {fname}: {lines}{marker}")

    console.print()
    console.print(Panel(table, title="[bold]vibe status[/]"))


# ─── vibe adapt ──────────────────────────────────────────────────────────────


@app.command()
def adapt(
    add: str | None = typer.Option(None, help="Add an adapter (e.g., claude, cursor)"),
    remove: str | None = typer.Option(None, help="Remove an adapter"),
    list_adapters: bool = typer.Option(False, "--list", help="List enabled adapters"),
    sync_adapters: bool = typer.Option(False, "--sync", help="Re-sync all adapter files"),
    confirm: bool = typer.Option(False, help="Confirm destructive operations"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without applying"),
) -> None:
    """Manage AI/IDE adapter files."""
    vibe_dir = _vibe_dir()
    _require_lifecycle("adapt")

    config = load_config(vibe_dir)

    if list_adapters:
        from vibe_state.adapters.registry import get_all_adapter_names

        all_names = sorted(get_all_adapter_names())
        enabled = set(config.adapters.enabled)
        console.print("[bold]Adapters:[/]")
        for name in all_names:
            mark = "[green]ON [/]" if name in enabled else "[dim]OFF[/]"
            console.print(f"  {mark}  {name}")
        return

    if add:
        from vibe_state.adapters.registry import get_all_adapter_names

        valid_names = get_all_adapter_names()
        if add not in valid_names:
            console.print(
                f"[red]Error:[/] Unknown adapter '{add}'.\n"
                f"Available: {', '.join(valid_names)}"
            )
            raise typer.Exit(1)
        if add in config.adapters.enabled:
            console.print(f"[yellow]{add} is already enabled.[/]")
            return
        config.adapters.enabled.append(add)
        save_config(vibe_dir, config)
        console.print(f"[green]Added adapter:[/] {add}")
        console.print("[dim]Run [bold]vibe adapt --sync[/bold] to generate config files.[/dim]")
        return

    if remove:
        if remove not in config.adapters.enabled:
            console.print(f"[yellow]{remove} is not enabled.[/]")
            return
        adapter = get_adapter(remove)
        if not adapter:
            console.print(f"[red]Unknown adapter:[/] {remove}")
            return
        files_to_remove = adapter.clean(Path.cwd())
        if dry_run:
            console.print(f"[dim]Would remove adapter:[/] {remove}")
            for f in files_to_remove:
                console.print(f"  [dim]- {f.relative_to(Path.cwd())}[/]")
            console.print("[dim](dry-run, no files changed)[/]")
            return
        if not confirm:
            from vibe_state.safety import has_user_modifications

            modified = has_user_modifications(vibe_dir, remove, files_to_remove)
            if modified:
                console.print("[yellow]Warning:[/] These files have been manually edited:")
                for f in modified:
                    console.print(f"  - {f.relative_to(Path.cwd())}")
            console.print(
                f"[yellow]This will remove {len(files_to_remove)} file(s) for {remove}.[/]\n"
                f"Use [bold]--confirm[/bold] to execute or [bold]--dry-run[/bold] to preview."
            )
            return

        # Execute removal with backup
        from vibe_state.safety import create_backup

        if files_to_remove:
            backup_dir = create_backup(vibe_dir, remove, files_to_remove)
            for f in files_to_remove:
                f.unlink(missing_ok=True)
            console.print(f"[green]Removed {len(files_to_remove)} file(s) for {remove}[/]")
            console.print(f"[dim]Backup: {backup_dir.relative_to(Path.cwd())}[/]")
        config.adapters.enabled.remove(remove)
        save_config(vibe_dir, config)
        return

    if sync_adapters:
        from vibe_state.safety import has_user_modifications, save_snapshot

        ctx = build_adapter_context(Path.cwd())
        total_files = 0
        for adapter_name in config.adapters.enabled:
            adapter = get_adapter(adapter_name)
            if not adapter:
                console.print(f"[yellow]Unknown adapter:[/] {adapter_name}")
                continue
            existing_files = adapter.clean(Path.cwd())
            modified = has_user_modifications(vibe_dir, adapter_name, existing_files)
            if modified and not confirm:
                msg = "files modified by user, use --confirm to overwrite"
                console.print(f"[yellow]{adapter_name}:[/] {msg}")
                for f in modified:
                    console.print(f"  - {f.relative_to(Path.cwd())}")
                continue
            emitted = adapter.emit(ctx)
            save_snapshot(vibe_dir, adapter_name, emitted)
            total_files += len(emitted)
            console.print(f"[green]{adapter_name}:[/] {len(emitted)} file(s) synced")
        console.print(f"\n[bold]Total:[/] {total_files} adapter file(s) synced.")
        return

    console.print("[yellow]Specify --add, --remove, --list, or --sync.[/]")
