"""Migrate existing AI config files into .vibe/ state.

Detects legacy files (CLAUDE.md, .cursorrules, AGENTS.md, etc.),
extracts useful rules, imports them into .vibe/state/standards.md,
and offers to clean up the originals.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger("vibe.migrator")

# Files we know how to read and migrate
LEGACY_FILES: dict[str, list[str]] = {
    "CLAUDE.md": ["CLAUDE.md", ".claude/CLAUDE.md"],
    "AGENTS.md": ["AGENTS.md"],
    "GEMINI.md": ["GEMINI.md"],
    ".cursorrules": [".cursorrules"],
    ".windsurfrules": [".windsurfrules"],
}


@dataclass
class MigrationResult:
    """Result of scanning for legacy files."""

    found_files: list[Path] = field(default_factory=list)
    extracted_rules: list[str] = field(default_factory=list)
    total_lines_imported: int = 0
    has_unstructured_content: bool = False
    files_without_rules: list[Path] = field(default_factory=list)  # Per-file tracking


def scan_legacy_files(project_root: Path) -> MigrationResult:
    """Scan for existing AI config files that can be migrated."""
    result = MigrationResult()

    for _label, paths in LEGACY_FILES.items():
        for rel_path in paths:
            full_path = project_root / rel_path
            if full_path.exists() and full_path.is_file():
                # Skip files generated by vibe (have integrity marker)
                content = full_path.read_text(encoding="utf-8", errors="replace")
                if "vibe-state-cli:" in content:
                    logger.debug("Skipping vibe-generated file: %s", rel_path)
                    continue

                result.found_files.append(full_path)
                rules = _extract_rules(content)
                if rules:
                    result.extracted_rules.extend(rules)
                    result.total_lines_imported += len(rules)
                    logger.debug(
                        "Extracted %d rules from %s", len(rules), rel_path
                    )
                else:
                    result.files_without_rules.append(full_path)
                    if len(content.strip()) > 50:
                        result.has_unstructured_content = True
                break  # Only first match per label

    # Also check .cursor/rules/*.mdc for hand-written rules
    cursor_rules = project_root / ".cursor" / "rules"
    if cursor_rules.is_dir():
        for mdc in cursor_rules.glob("*.mdc"):
            content = mdc.read_text(encoding="utf-8", errors="replace")
            if "vibe-state-cli:" in content:
                continue
            result.found_files.append(mdc)
            rules = _extract_rules(content)
            if rules:
                result.extracted_rules.extend(rules)
                result.total_lines_imported += len(rules)

    # Check .clinerules/
    clinerules = project_root / ".clinerules"
    if clinerules.is_dir():
        for md in clinerules.glob("*.md"):
            content = md.read_text(encoding="utf-8", errors="replace")
            if "vibe-state-cli:" in content:
                continue
            result.found_files.append(md)
            rules = _extract_rules(content)
            if rules:
                result.extracted_rules.extend(rules)
                result.total_lines_imported += len(rules)

    return result


def _extract_rules(content: str) -> list[str]:
    """Extract actionable rule lines from a config file.

    Looks for lines starting with `- ` that contain actual instructions,
    skipping headers, blank lines, and boilerplate.
    """
    rules: list[str] = []
    seen: set[str] = set()

    for line in content.splitlines():
        stripped = line.strip()
        # Only take bullet-point rules
        if not stripped.startswith("- "):
            continue
        # Skip obvious boilerplate
        if stripped in ("- (none)", "- (empty)"):
            continue
        # Deduplicate
        if stripped in seen:
            continue
        seen.add(stripped)
        rules.append(stripped)

    return rules


def build_imported_standards(rules: list[str]) -> str:
    """Build a review section from imported legacy rules.

    Rules are placed in a 'Needs Review' section with instructions
    for the AI to help the user clean them up on first session.
    """
    if not rules:
        return ""
    lines = [
        "",
        "## Imported — NEEDS REVIEW",
        "",
        "The following rules were extracted from legacy config files.",
        "On your first session, help the human:",
        "1. Remove duplicates and outdated rules",
        "2. Merge related rules into concise statements",
        "3. Move finalized rules to the section above",
        "4. Delete this section when done",
        "",
    ]
    lines.extend(rules)
    lines.append("")
    return "\n".join(lines)
